female(jenna).
female(lynn).
female(emmy).
female(greta).
female(laura).
female(daisy).

male(carlos).
male(frederick).
male(harry).
male(william).
male(zyan).
male(adam).

parent(emmy,frederick).
parent(carlos,adam).
parent(harry,greta).
parent(carlos,jenna).
parent(harry,frederick).
parent(frederick,lynn).
parent(laura,lynn).
parent(frederick,william).
parent(lynn,jenna).
parent(harry,zyan).
parent(jenna,daisy).
mother(X,Y):-parent(X,Y),female(X).
father(X,Y):-parent(X,Y),male(X).
sister(X,Y):-female(X),parent(Z,X),parent(Z,Y).`
brother(X,Y):-male(X),parent(Z,X),parent(Z,Y).
wife(X,Y):-parent(X,Z),parent(Y,Z),female(X),male(Y).
husband(X,Y):-parent(X,Z),parent(Y,Z),male(X),female(Y).
uncle(X,Y):-male(X),brother(X,Z),parent(Z,Y).
aunt(X,Y):-female(X),sister(X,Z),parent(Z,Y).
