male(jack).
male(oliver).
male(ali).
male(james).
male(simon).
male(harry).
female(hellen).
female(sophie).
female(lily).
female(jess).
parent(jack,jess).
parent(jack,lily).
parent(hellen,jess).
parent(hellen,lily).
parent(oliver,james).
parent(sophie,james).
parent(jess,simon).
parent(ali,simon).
parent(lily,harry).
parent(james,harry).
father_of(X,Y):-male(X),parent(X,Y).
mother_of(X,Y):-female(X),parent(X,Y).
g_father(X,Y):-male(X),parent(X,Z),parent(Z,Y).
g_mother(X,Y):-female(X),parent(X,Z),parent(Z,Y).
